### ISSUE TITLE
Profile page for each fellow

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/jan-2022-prep-portfolio#10]
When you click on each fellows card, it sends you to a separate page which includes more detail such as:

- Description
- Favourite programming languages
- Interests outside of technology
- University

**Comment by harshsharma6401** [comment]
I would love to work on this!

**Comment by adizcode** [comment]
Sounds interesting. Let's work on this together @harshsharma6401

**Comment by harshsharma6401** [comment]
Sure!

**Comment by Chukwuemeka-Mba** [comment]
Would love to join you guys on this @adizcode @harshsharma6401

**Comment by harshsharma6401** [comment]
> Would love to join you guys on this @adizcode @harshsharma6401 
The feeling is mutual!
