### ISSUE TITLE
Add the pod!

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/jan-2022-prep-portfolio#14]
Currently, then repository has members of the MLH team on it, but you should replace them with members of the pod.

You can update information in `_data/fellows.yml`

You should work on:
- [ ] Replacing the images
- [ ] Update the names and locations of each fellow
- [ ] Update the pod number inside of `_config.yml`

**Comment by Chukwuemeka-Mba** [comment]
I'm guessing @Aniket762 is done with this issue

**Comment by Aniket762** [comment]
Hey @Chukwuemeka-Mba , we as in me and @adizcode are already working on it 🐣

**Comment by yyjlincoln** [comment]
Merged.
