### ISSUE TITLE
Encourage uniform basic code style

### ISSUE THREAD

**Issue by ditsuke** [MLH-Fellowship/jan-2022-prep-portfolio#19]
The code that's being added via PRs should follow the same style as existing code (indentation, line endings, end of file newline) for consistency and clean diffs. I propose an [EditorConfig](https://editorconfig.org) file for a frictionless experience.

**Comment by yyjlincoln** [comment]
Sounds great to me! I was having the same issue as well earlier when reading code from other contributors. Do you know how to set it up? Should we discuss it in the next meeting?

**Comment by ditsuke** [comment]
> Sounds great to me! I was having the same issue as well earlier when reading code from other contributors. Do you know how to set it up? Should we discuss this in our next meeting?

Thanks for supporting! All we need is a `.editorconfig` file with the right configuration. I believe I have one set up already so I can open a PR once we have enough support per @gmelodie, lets convince everyone in today's standup 😀

**Comment by yyjlincoln** [comment]
Sounds great!
