### ISSUE TITLE
Add header background

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/jan-2022-prep-portfolio#4]
At the moment, the header background is a colour. Have an option to add an image that's easy to swap to something else and works on multiple screen sizes.

**Comment by harshsharma6401** [comment]
I would like to work on this !

**Comment by KhudaDad414** [comment]
Me too.

**Comment by KhudaDad414** [comment]
Me too.

**Comment by ditsuke** [comment]
Let's team up @harshsharma6401
