### ISSUE TITLE
What should be the metric for contribution?

### ISSUE THREAD

**Issue by KhudaDad414** [MLH-Fellowship/jan-2022-prep-portfolio#42]
## Context
As part of #5 we are adding a leaderboard to the website that shows who are the top contributors.
Currently, we are taking into account the number of commits each fellow pushes plus the total number of issues they opened. As you might have noticed the number of commits isn't a good metric since one fellow can push all of their code in one commit and some fellow like to push a commit for each small task.
IMO we should consider the number of reviews as well.
What do you think should be the metric of contribution?

**Comment by Aniket762** [comment]
0.4 * (num of commits) + 0.2 * (num of issues opened) + 0.4 * ( number of PRs merged) , generate a score from this and then you may rank people.

What if we follow this approach? @KhudaDad414 @CIPHERTron

**Comment by Dhruv-Sachdev1313** [comment]
I think No. of PRs should not be a major factor, as 2 people were working on one issue, and only one of them would be making a pull request. This in my opinion can shadow the other person's efforts. I can be completely wrong here🙈. But I think commits with reviews can be a good metric!

**Comment by yyjlincoln** [comment]
> I think No. of PRs should not be a major factor, as 2 people were working on one issue, and only one of them would be making a pull request. This in my opinion can shadow the other person's efforts. I can be completely wrong here🙈. But I think commits with reviews can be a good metric!

Agreed. Commits are better. Or possibly the sum of the total number of additions (lines of code added/deleted)?

**Comment by Dhruv-Sachdev1313** [comment]
Just a quick question, is it necessary to rank everyone? Can we just have a table(maybe alphabetically arranged) that has the list of all the fellow names and we would just display the commits, reviews, and maybe PRs by that person?

**Comment by KhudaDad414** [comment]
@Dhruv-Sachdev1313 I like this idea since there is no perfect way that we can count the contributions. maybe a board the shows the number of issues opened by each fellow and the number of commits and reviews?

**Comment by ditsuke** [comment]
I still like the idea of a stat board, that and we don't sort it by any metric. Sounds good.

**Comment by KhudaDad414** [comment]
I am closing this issue since we have reached a conclusion.
