### ISSUE TITLE
Profile images looks weird

### ISSUE THREAD

**Issue by yyjlincoln** [MLH-Fellowship/jan-2022-prep-portfolio#44]
<img width="2352" alt="Screen Shot 2022-01-14 at 07 10 26" src="https://user-images.githubusercontent.com/20881008/149402010-f6c0c65b-ce4c-4e67-8f2a-77eba4f839c8.png">

Can anybody fix it?

**Comment by CIPHERTron** [comment]
Yupp. I can work on this. Should be an easy fix if we use `object-fit: cover` 🤔
