### ISSUE TITLE
Social icons look weird in dark mode

### ISSUE THREAD

**Issue by yyjlincoln** [MLH-Fellowship/jan-2022-prep-portfolio#45]
<img width="2352" alt="Screen Shot 2022-01-14 at 07 11 54" src="https://user-images.githubusercontent.com/20881008/149402212-1a1c8146-48db-4b46-b026-9bccf8b09884.png">

Consider using `dark-only` and `light-only` classes. As they're recently merged into `main`, you might wish to branch again (if you're starting from scratch) or merge `main` to your existing branch to make these classes available.

**Comment by anubhav06** [comment]
How about this ? 
(I'm not good at CSS but I just tried 😅)<br><br>
![1](https://user-images.githubusercontent.com/43821031/149507567-b5903ecd-658f-4418-b07b-cd203637af54.png)

**Comment by anubhav06** [comment]
How about something like this?
(I am not good at CSS but I just tried 😅) <br>
![Uploading 1.png…]()
