### ISSUE TITLE
Contribution count is failing on PR pushes

### ISSUE THREAD

**Issue by yyjlincoln** [MLH-Fellowship/jan-2022-prep-portfolio#58]
It seems that the Contribution Count is failing on PR pushes but not when merging to main. Can we change its setting so that it only runs when there's a commit to `main` (including merge commits) so that it doesn't fail on PR branches?

[Log here](https://github.com/MLH-Fellowship/jan-2022-prep-portfolio/actions/runs/1699220149)

**Comment by harshsharma6401** [comment]
Yes, it has done this with my PR Twice!

**Comment by yyjlincoln** [comment]
Seems to be working now. Not sure why though - Probably one of the merges fixed it.
