### ISSUE TITLE
Contribution count action has the wrong stats

### ISSUE THREAD

**Issue by yyjlincoln** [MLH-Fellowship/jan-2022-prep-portfolio#59]
Many people are getting 0 commits. What went wrong?
@CIPHERTron @KhudaDad414 Do you want to double check? Not sure what's the issue. Probably because the action was triggered by a merge?

**Comment by yyjlincoln** [comment]
This is probably a duplicate of #57.

**Comment by KhudaDad414** [comment]
@yyjlincoln Tomorrow I will do a few queries and update the counts. Fell free to do so if you have some time to spare 🤠
