### ISSUE TITLE
Replace the MLH Fellowship logo with the MLH Prep logo

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/jan-2022-prep-portfolio#6]
![Screenshot 2021-09-30 at 18 38 57](https://user-images.githubusercontent.com/34094921/135504106-3f0aacc8-4155-463e-ae81-9433ad10ea13.png)

When you go to the project page, it shows the MLH Fellowship logo at the top. It would be great to replace this with the Prep logo and make sure that's used throughout the website!

**Comment by Riyadevvarshney11** [comment]
Interested

**Comment by kishdubey** [comment]
I believe this issue has already been resolved. Going to https://prep-jan-2022.netlify.app/, this is shown.

![image](https://user-images.githubusercontent.com/44308612/148844681-62d638fe-260f-43ba-9afb-26b0fb6ac7e4.png)

**Comment by anubhav06** [comment]
> I believe this issue has already been resolved. Going to https://prep-jan-2022.netlify.app/, this is shown.
> 
> ![image](https://user-images.githubusercontent.com/44308612/148844681-62d638fe-260f-43ba-9afb-26b0fb6ac7e4.png)

Nope. This issue is for this page: https://prep-jan-2022.netlify.app/projects/project  
Initially I had also thought the same 😄

**Comment by anubhav06** [comment]
@gmelodie @kishdubey The issue was for this page: https://prep-jan-2022.netlify.app/projects/project
It contains the fellowship logo, which we have replaced with the prep logo

**Comment by anubhav06** [comment]
#39 Merged
