### ISSUE TITLE
Only ask for the user's location after clicking a button

### ISSUE THREAD

**Issue by yyjlincoln** [MLH-Fellowship/jan-2022-prep-portfolio#60]
Currently, the page asks for the user's location every time you open the website. This can be annoying/intimidating to a user.

Can we add a button that, upon click, asks for the user's location and update the map (or otherwise, refresh the page)? Like a button/link "Show my location on the map"

https://web.dev/geolocation-on-start/

![image](https://user-images.githubusercontent.com/20881008/149576248-948fd6ba-7426-405d-8628-2be5d2b315a5.png)

**Comment by ditsuke** [comment]
On it!
