### ISSUE TITLE
Consider hiding profile images in index.html when viewed on mobile.

### ISSUE THREAD

**Issue by yyjlincoln** [MLH-Fellowship/jan-2022-prep-portfolio#64]
It takes a long time to scroll to the bottom of the page on a phone. Consider adding a `@media` rule to hide the profile images and only show them on larger screens.

![image](https://user-images.githubusercontent.com/20881008/149597311-9fd6ff40-19cf-4704-aa9a-35f3aa619233.png)

**Comment by Chukwuemeka-Mba** [comment]
I'd like to work with you on this one @yyjlincoln

**Comment by yyjlincoln** [comment]
> I'd like to work with you on this one @yyjlincoln 

Hey! Unfortunately I won't be working on this issue as I have something else to do. Feel free to work on it yourself or find another teammate! Good luck!

**Comment by SinghShreyansh** [comment]
I can do this , plz assign this to me

**Comment by yyjlincoln** [comment]
Hey @SinghShreyansh, thanks for your contribution to our portfolio page & thanks for your PR. I will invite our pod members to review your PR, and if there are a few approvals & no rejections, we will merge your PR.
I've assigned this issue to you and @Chukwuemeka-Mba.

**Comment by SinghShreyansh** [comment]
Okay 👍 @yyjlincoln , Hoping for good . This is my first PR to open source project .

**Comment by ditsuke** [comment]
Closed with #70
