### ISSUE TITLE
Add pod blog

### ISSUE THREAD

**Issue by wrussell1999** [MLH-Fellowship/jan-2022-prep-portfolio#8]
It would be awesome to add a blog feature to this repository where fellows can share their insights and people can tune in!

**Comment by kishdubey** [comment]
This sounds like a pretty cool feature. Would like to try this out. Any other fellows interested, please let me know, and we can pair program our way through it.

**Comment by psahithireddy** [comment]
I am interested

**Comment by psahithireddy** [comment]
Hi @kishdubey lets start working on this
